Add all initial migrations for DB.
Awesomeness-Inkorporated/awesomazon pull request #1
Opened 2020-10-05 18:12 UTC by KiriKaz

2020-10-06 16:38 UTC, KiriKaz commented
I walked @MaiBaka through making a necessary change, one of the lines was off, so I walked him through checking out a branch, setting up his git with git config, and pushing the change he made.

2020-10-07 07:52 UTC, hoodedice requested changes

2020-10-07 07:52 UTC, hoodedice commented on database/migrations/2020_10_05_160539_create_addresses_table.php
> +        Schema::create('addresses', function (Blueprint $table) {
All fields except `id`, `contact_name` and the ones created by `->timestampsTz()` are nullable, please add on 
`->nullable()`

2020-10-07 07:52 UTC, hoodedice commented on database/migrations/2020_10_05_162247_create_stores_table.php
> +        Schema::create('stores', function (Blueprint $table) {
let's set `description`, `url`, `address_id`, and `image` as nullable here

2020-10-07 07:52 UTC, hoodedice commented on database/migrations/2020_10_05_163124_create_products_table.php
> +        Schema::create('products', function (Blueprint $table) {
`image`, `meta`, `warranty_text` should be nullable here

2020-10-07 07:52 UTC, hoodedice commented on database/migrations/2020_10_05_170401_create_reviews_table.php
> +        Schema::create('reviews', function (Blueprint $table) {
`comment` is nullable here

2020-10-07 07:53 UTC, hoodedice commented
Good work so far @KiriKaz 
I think we'll let @MaiBaka deal with the changes I've requested. Once that's done I'll approve and we can merge these changes in

2020-10-07 19:32 UTC, hoodedice requested changes

2020-10-07 19:32 UTC, hoodedice commented on database/migrations/2020_10_05_162247_create_stores_table.php
> +            $table->foreignId('address_id')->nullable();
You still need to keep the `->constrained()` at the end!
`$table->foreignId('address_id')->nullable()->constrained();`

2020-10-11 11:14 UTC, hoodedice approved these changes
:+1: Good to merge

2020-10-11 16:26 UTC, merged